### ISSUE TITLE
User Interface and Output Formatting Improvements

### ISSUE THREAD

**Issue by WillBreak** [Berat-O/Python_Project#12]
**Is your feature request related to a problem? Please describe.**
Hi! I've been looking for some ways to begin contributing to projects. I'd love to generally enhance the user experience for this program, providing clearer menu options and presenting the stock data output in tabular form.

**Describe the solution you'd like**
-Improving the instruction messages to the user, making it clearer what they are required to input.
-Validating their input and confirming how they can reach the desired output.
-Modifying the `dispay_data()`  method to present the data in an easy-to-read table

**Additional context**
I believe these changes will contribute to a more positive user experience by enhancing usability of the program.

Thanks!

**Comment by Berat-O** [comment]
Thank you for the suggestion! A web interface could greatly expand the reach of our project, allowing users to access it from any device with internet connectivity. We'll explore the possibility of creating a web interface to provide a seamless user experience.

Your input is valuable, and I excited to consider this enhancement. Feel free to share any additional ideas you may have!
